Various updates
* Use Ubuntu 18.04 & FreeBSD 11.1
* Update gcc, binutils, etc to newer versions
* Fix `fix-links` to work with FreeBSD 11.1
* `build` now takes a docker tag argument instead of hard-coding it
  to freebsd-cross-build.
* Verify the FreeBSD image with sha256 since that's what FreeBSD
  provides
* Get the FreeBSD image from ftp-archive.  ftp4.us only has newer
  images.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,27 +1,33 @@
 #!/bin/sh
 
+function usage {
+  echo "Usage: $0 <docker tag>"
+}
+[ -z "$1" ] && usage && exit 1
+
+tag="$1"
+
 x() {
     n=$(basename "$1")
     [ -f "$n" ] && echo "$n already fetched" || wget "$1"
 }
-x http://ftp.gnu.org/gnu/binutils/binutils-2.25.1.tar.gz
-x http://ftp.gnu.org/gnu/gmp/gmp-6.0.0a.tar.xz
-x http://ftp4.us.freebsd.org/pub/FreeBSD/releases/ISO-IMAGES/9.3/FreeBSD-9.3-RELEASE-amd64-dvd1.iso
-x http://ftp.gnu.org/gnu/mpfr/mpfr-3.1.3.tar.xz
-x http://ftp.gnu.org/gnu/mpc/mpc-1.0.3.tar.gz
-x http://ftp.gnu.org/gnu/gcc/gcc-4.8.5/gcc-4.8.5.tar.bz2
+x http://ftp.gnu.org/gnu/binutils/binutils-2.33.1.tar.gz
+x http://ftp.gnu.org/gnu/gmp/gmp-6.1.2.tar.xz
+x http://ftp-archive.freebsd.org/pub/FreeBSD-Archive/old-releases/ISO-IMAGES/11.1/FreeBSD-11.1-RELEASE-amd64-dvd1.iso
+x http://ftp.gnu.org/gnu/mpfr/mpfr-4.0.2.tar.xz
+x http://ftp.gnu.org/gnu/mpc/mpc-1.1.0.tar.gz
+x http://ftp.gnu.org/gnu/gcc/gcc-7.4.0/gcc-7.4.0.tar.gz
 
-S=$(sha1sum FreeBSD-9.3-RELEASE-amd64-dvd1.iso | awk '{print $1}')
-if [ "$S" != "9332445f4ecfc9ff4095031e0342ee72884493f1" ]
+S=$(sha256sum FreeBSD-11.1-RELEASE-amd64-dvd1.iso | awk '{print $1}')
+if [ "$S" != "49e8f32e0a097a1ab411cb85f1adf6d78ba931ff557a07cd1e84af62a47c2d6f" ]
 then
-    >&2 echo "Error: sha1sum does not match"
+    >&2 echo "Error: sha256sum does not match"
     exit 1
 fi
 mkdir -p freebsd
-(cd freebsd; 7z x ../FreeBSD-9.3-RELEASE-amd64-dvd1.iso usr/include)
-(cd freebsd; 7z x ../FreeBSD-9.3-RELEASE-amd64-dvd1.iso usr/lib)
-(cd freebsd; 7z x ../FreeBSD-9.3-RELEASE-amd64-dvd1.iso lib)
+(cd freebsd; 7z x ../FreeBSD-11.1-RELEASE-amd64-dvd1.iso usr/include)
+(cd freebsd; 7z x ../FreeBSD-11.1-RELEASE-amd64-dvd1.iso usr/lib)
+(cd freebsd; 7z x ../FreeBSD-11.1-RELEASE-amd64-dvd1.iso lib)
 
-docker build -t freebsd-cross-build .
+docker build -t $tag .
 exit 0
-
